In [17]:
import pandas as pd 
from sklearn.datasets import load_digits
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.model_selection import KFold
from sklearn.ensemble import RandomForestClassifier
import numpy as np 

digits = load_digits()
kf = KFold(n_splits=3)

In [20]:
def get_score(model,X_train, X_test, y_train, y_test):
    model.fit(X_train,y_train)
    return model.score(X_test, y_test)

In [24]:
# НЕОБЯЗАТЕЛЬНО

score1 = []
score2 = []
score3 = []

for train_index, test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index],\
                                digits.target[train_index], digits.target[test_index]
    score1.append(get_score(LogisticRegression(solver='liblinear', max_iter=1000),X_train, X_test, y_train, y_test))
    score2.append(get_score(SVC(),X_train, X_test, y_train, y_test))
    score3.append(get_score(RandomForestClassifier(),X_train, X_test, y_train, y_test))

In [25]:
score1

[0.8964941569282137, 0.9515859766277128, 0.9115191986644408]

In [26]:
score2

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [27]:
score3

[0.9332220367278798, 0.9482470784641068, 0.9165275459098498]

In [30]:
# ВАЖНО!!!

from sklearn.model_selection import cross_val_score

cross_val_score(LogisticRegression(solver='liblinear', max_iter=1000),digits.data, digits.target)

array([0.92222222, 0.88333333, 0.95264624, 0.95821727, 0.89415042])

In [31]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [32]:
cross_val_score(RandomForestClassifier(),digits.data, digits.target)

array([0.93333333, 0.91388889, 0.9637883 , 0.95821727, 0.93036212])

In [40]:
cross_val_score(RandomForestClassifier(),digits.data, digits.target)

array([0.93055556, 0.91111111, 0.95821727, 0.97214485, 0.92200557])

In [43]:
# HOMEWORK

from sklearn.datasets import load_iris

iris = load_iris()
cross_val_score(RandomForestClassifier(),iris.data,iris.target)

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [44]:
cross_val_score(SVC(),iris.data,iris.target)

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [48]:
cross_val_score(LogisticRegression(max_iter=1000),iris.data,iris.target)

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])