In [16]:
import pandas as pd 

df = pd.read_csv("csv/titanic.csv")
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [17]:
df.drop(['Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)

In [18]:
df.head()

PassengerId  Survived  Pclass     Sex   Age     Fare
0            1         0       3    male  22.0   7.2500
1            2         1       1  female  38.0  71.2833
2            3         1       3  female  26.0   7.9250
3            4         1       1  female  35.0  53.1000
4            5         0       3    male  35.0   8.0500

In [19]:
target=df.Survived
inp = df.drop('Survived',axis='columns')

In [22]:
dum = pd.get_dummies(inp.Sex)
dum.head()
inp = pd.concat([inp,dum],axis='columns')
inp.drop('Sex',axis='columns',inplace=True)

AttributeError: 'DataFrame' object has no attribute 'Sex'

In [24]:
inp.head(3)

PassengerId  Pclass   Age     Fare  female  male
0            1       3  22.0   7.2500       0     1
1            2       1  38.0  71.2833       1     0
2            3       3  26.0   7.9250       1     0

In [26]:
inp.columns[inp.isna().any()]

Index(['Age'], dtype='object')

In [34]:
inp.Age = inp.Age.fillna(inp.Age.mean())
inp.head()

PassengerId  Pclass   Age     Fare  female  male
0            1       3  22.0   7.2500       0     1
1            2       1  38.0  71.2833       1     0
2            3       3  26.0   7.9250       1     0
3            4       1  35.0  53.1000       1     0
4            5       3  35.0   8.0500       0     1

In [68]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inp, target, test_size=0.2)

In [69]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.7597765363128491

In [62]:
X_test.head()

PassengerId  Pclass        Age   Fare  female  male
330          331       3  29.699118  23.25       1     0
241          242       3  29.699118  15.50       1     0
586          587       2  47.000000  15.00       0     1
792          793       3  29.699118  69.55       1     0
760          761       3  29.699118  14.50       0     1

In [65]:
X_test.head()

PassengerId  Pclass        Age   Fare  female  male
330          331       3  29.699118  23.25       1     0
241          242       3  29.699118  15.50       1     0
586          587       2  47.000000  15.00       0     1
792          793       3  29.699118  69.55       1     0
760          761       3  29.699118  14.50       0     1

In [64]:
model.predict(X_test[:10])

array([1, 1, 0, 1, 0, 0, 0, 0, 0, 0])

In [70]:
model.predict_proba(X_test)

array([[2.16470135e-02, 9.78352987e-01],
       [4.11418488e-02, 9.58858151e-01],
       [5.94567147e-02, 9.40543285e-01],
       [9.88602910e-01, 1.13970902e-02],
       [8.08504294e-01, 1.91495706e-01],
       [9.90613062e-01, 9.38693778e-03],
       [2.98598125e-70, 1.00000000e+00],
       [9.90656755e-01, 9.34324509e-03],
       [9.89430726e-01, 1.05692741e-02],
       [2.59748005e-01, 7.40251995e-01],
       [2.17936017e-02, 9.78206398e-01],
       [9.91367946e-01, 8.63205373e-03],
       [3.60251813e-02, 9.63974819e-01],
       [9.89405815e-01, 1.05941848e-02],
       [9.87069989e-01, 1.29300108e-02],
       [3.30150935e-02, 9.66984907e-01],
       [5.89960140e-02, 9.41003986e-01],
       [9.90744141e-01, 9.25585931e-03],
       [9.89907860e-01, 1.00921401e-02],
       [6.13792318e-02, 9.38620768e-01],
       [6.21524704e-02, 9.37847530e-01],
       [9.73958773e-01, 2.60412274e-02],
       [9.72387027e-01, 2.76129731e-02],
       [9.74957455e-01, 2.50425447e-02],
       [9.902501

In [253]:
df = pd.read_csv('csv/spam.csv')
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [254]:
df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [255]:
df['spam'] = df['Category'].apply(lambda x: 1 if x == 'spam' else 0)

In [256]:
df.drop('Category',axis='columns',inplace = True)

In [257]:
df.head(3)

Message  spam
0  Go until jurong point, crazy.. Available only ...     0
1                      Ok lar... Joking wif u oni...     0
2  Free entry in 2 a wkly comp to win FA Cup fina...     1

In [258]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(df.Message,df.spam,test_size=0.25)

In [259]:
# данная хуйня берет слова которые повторяются бОльшее кол-во раз. 
from sklearn.feature_extraction.text import CountVectorizer

vect = CountVectorizer()

In [260]:
# помещаем значения обучающей выборки в модель после чего трансформируем его в вектора

X_train_count = vect.fit_transform(X_train.values)
X_train_count.toarray()[:3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [261]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_count,y_train)

MultinomialNB()

In [262]:
emails = [
    'Hey dude whatsupp how are u doing',
    'Upto 20% discount in our store ! weekends are free food. join to our partnership'
]
email_count = vect.transform(emails)
model.predict(email_count)

array([0, 1])

In [263]:
x_test_count = vect.transform(X_test.values)
model.score(x_test_count, y_test)

0.9863603732950467

In [266]:
from sklearn.pipeline import Pipeline

clf=Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [270]:
clf.fit(X_train, y_train)

2229                       Those were my exact intentions
4769           I'm not sure if its still available though
177                            U still going to the mall?
965                                Are you this much buzy
5211                      It is only yesterday true true.
                              ...                        
1629            Yes princess! I want to make you happy...
3874    Happy or sad , one thing about past is- "Its n...
5230                        Nope, I'm still in the market
879     U have a secret admirer who is looking 2 make ...
2077            Trust me. Even if isn't there, its there.
Name: Message, Length: 1393, dtype: object

In [272]:
clf.score(X_test,y_test)

0.9863603732950467

In [281]:
from sklearn import datasets
wine = datasets.load_wine()
df = pd.DataFrame(wine.data, columns=wine.feature_names)
df['target'] = wine.target

In [288]:
X_train, X_test, y_train, y_test = train_test_split(df.drop('target',axis='columns'),df.target,test_size=0.3)
model = GaussianNB()
model.fit(X_train, y_train)

GaussianNB()

In [292]:
X_test.head(5)

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
122    12.42        4.43  2.73               26.5      102.0           2.20   
3      14.37        1.95  2.50               16.8      113.0           3.85   
118    12.77        3.43  1.98               16.0       80.0           1.63   
113    11.41        0.74  2.50               21.0       88.0           2.48   
141    13.36        2.56  2.35               20.0       89.0           1.40   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
122        2.13                  0.43             1.71             2.08  0.92   
3          3.49                  0.24             2.18             7.80  0.86   
118        1.25                  0.43             0.83             3.40  0.70   
113        2.01                  0.42             1.44             3.08  1.10   
141        0.50                  0.37             0.64             5.60  0.70   

     od280/od315_of_diluted_wines  proline  
122                          3.12    365.0  
3                            3.45   1480.0  
118                          2.12    372.0  
113                          2.31    434.0  
141                          2.47    780.0

In [293]:
model.predict(X_test)

array([1, 0, 1, 1, 2, 1, 0, 0, 2, 0, 1, 0, 2, 1, 2, 0, 0, 1, 2, 0, 1, 0,
       0, 2, 2, 1, 1, 2, 1, 1, 1, 2, 2, 1, 2, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 2])

In [289]:
model.score(X_test, y_test)

0.9814814814814815

In [286]:
model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB()

In [287]:
model.score(X_test, y_test)

0.7777777777777778

In [11]:
import pandas as pd 

df = pd.read_csv("csv/titanic.csv")
df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [12]:
# df.drop(['Name','SibSp','Parch','Ticket','Cabin','Embarked','Fare','Pclass'],axis='columns')
df['se_x'] = df.apply()

PassengerId  Survived     Sex   Age
0              1         0    male  22.0
1              2         1  female  38.0
2              3         1  female  26.0
3              4         1  female  35.0
4              5         0    male  35.0
..           ...       ...     ...   ...
886          887         0    male  27.0
887          888         1  female  19.0
888          889         0  female   NaN
889          890         1    male  26.0
890          891         0    male  32.0

[891 rows x 4 columns]